production:
  adapter: mysql
  database: openmrs_production 
  username: root
  password: 
  host: localhost

development:
  adapter: mysql
  database: bims_development
  username: root
  password: ben979
  host: localhost

test:
  adapter: mysql
  database: openmrs_test
  username: root
  password:
  host: localhost

